// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnMIl9N7rb0srRuFgi18NCxf7hUMScN8',
    appId: '1:211875988399:web:6315e319475d19a2d7e55a',
    messagingSenderId: '211875988399',
    projectId: 'task-daily-55121',
    authDomain: 'task-daily-55121.firebaseapp.com',
    storageBucket: 'task-daily-55121.appspot.com',
    measurementId: 'G-BYS50M19HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLbIl1KHnBqedOmWFXKNO4VXtDVaYjxTA',
    appId: '1:211875988399:android:510854114a58425cd7e55a',
    messagingSenderId: '211875988399',
    projectId: 'task-daily-55121',
    storageBucket: 'task-daily-55121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZOyNjUWH6B-psUIa1oAwUHPkR9ERTHk',
    appId: '1:211875988399:ios:edf311d59b77998fd7e55a',
    messagingSenderId: '211875988399',
    projectId: 'task-daily-55121',
    storageBucket: 'task-daily-55121.appspot.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZOyNjUWH6B-psUIa1oAwUHPkR9ERTHk',
    appId: '1:211875988399:ios:edf311d59b77998fd7e55a',
    messagingSenderId: '211875988399',
    projectId: 'task-daily-55121',
    storageBucket: 'task-daily-55121.appspot.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCnMIl9N7rb0srRuFgi18NCxf7hUMScN8',
    appId: '1:211875988399:web:52d662617f4b455dd7e55a',
    messagingSenderId: '211875988399',
    projectId: 'task-daily-55121',
    authDomain: 'task-daily-55121.firebaseapp.com',
    storageBucket: 'task-daily-55121.appspot.com',
    measurementId: 'G-9ZHSEJHXE3',
  );
}
